### ISSUE TITLE
Visible text is cut when container has white-space: pre-line

### ISSUE THREAD

**Issue by Dumk0** [yowainwright/shave#28] opened 2020-06-18 15:27 UTC
## What Is the issue?
Text is cut more than it should when containing element has
`white-space: pre-line` 
CSS style.

For example if I have container with with the following text (see empty lines between 2 sentenses).
```
Fun during any period of your a life.



Here goes text beyond the view area.
```
The container width is wide enough to fit text much longer than the first line of text.
The container (**\<p>** tag) has `white-space: pre-line` style.

I want to limit my view area to the size of 2-3 lines of text (lets say 70px).

I do `shave('p', 70)`

**Expected result**
I expect that only first line is visible but it shall be visible fully because text size is not so long and fits one line very well

**Actual result**
Last word in my line is cut and I see "Fun during any period of your a…"

[Working example on JSFiddle](https://jsfiddle.net/b1j5gt8m/87/)

**Comment by yowainwright** [comment] 2020-06-23 00:45
Seems to work with the [css style](https://jsfiddle.net/yowainwright/5e31mw64/1/) but not with the added line breaks. 

If the issue is receiving plain text with linebreaks, perhaps something like [this](https://stackoverflow.com/questions/21711768/split-string-in-javascript-and-detect-line-break#answer-44105598) will help you towards the right solution.

This issue won't be worked on because the issue fix would complicate the simplicity of this utility. ~Thanks for your thoughtful issue, though @Dumk0.

**Comment by yowainwright** [comment] 2020-06-23 14:51
Hey, @Dumk0 sorry, I accidentally closed this. That was poor etiquette. 

Would you mind closing this if you find my response satisfactory? 

~Jeff

**Comment by Dumk0** [comment] 2020-06-25 12:27
Hey @yowainwright 
sorry, but the main idea is use the text formatting as is (with line breaks). 
If it would be okay to have the block without formatting, then I would simply remove the `white-space: pre-line` style instead of stripping new lines.
Real use case is to have a short block to showing a text where several paragraphs may be used. So new lines is essential part of the text itself.

As a workaround I'm using `{spaces: false}` option, but it may case a situation when last line in the shaved block will be blank line and it would be good to not to have it there to save some space for other elements.

Can there be an option to trim white spaces from end of shaved text before js-shave-char element?

**Comment by yowainwright** [comment] 2020-06-25 17:45
@Dumk0 referencing my original response, no. The reason is Shave is a utility module meant to be small and fast. By providing only necessary features, it remains that—small and fast. When dealing with dom thrashing, this consideration  (being small and fast (kbs, processing speed) is especially important. 😄 

Regarding your initial issue, I think that there are other ways to address what I understand to be the problem. 

~Thanks again

**Closed** 2020-06-30 18:35 UTC
